language: node_js
node_js:
- '7'

cache:
  yarn: true

# https://yarnpkg.com/en/docs/install-ci#travis-tab
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    repo: Merlin-Taylor/emjen
    tags: true