module.exports = {
  $id: 'http://thetrainline.com/job-engine/message/RunTask-schema#',
  $schema: 'http://json-schema.org/draft-06/schema#',
  title: 'RunTask',
  description: 'A message requesting a worker run a task',
  type: 'object',
  properties: {
    Args: { type: 'object' },
    Command: { type: 'string' },
    JobId: { type: 'string' },
    ReplyTo: { type: 'string' },
    Seq: { type: 'integer', minimum: 0 },
    TaskId: { type: 'string' },
    TTL: { description: 'TTL (milliseconds elapsed since 1 January 1970 00:00:00 UTC)', type: 'integer', minimum: 0 },
    Type: { type: 'string', pattern: 'RunTask' },
    User: { type: 'string' },
  },
  required: [
    'Command',
    'JobId',
    'ReplyTo',
    'Seq',
    'TaskId',
    'TTL',
    'Type',
    'User',
  ],
};
